### ISSUE TITLE
gpgp: decrypt_message failed: No such file or directory

### ISSUE THREAD

**Issue by williamoconnorme** [jvalecillos/vscode-gpg#10]
After encrypting a message and attempting to decrypt after, the decryption fails and a message in developer console says that a tmp file can't be found.

The file I'm decrypting from is saved to disk.

![image](https://user-images.githubusercontent.com/978081/59928420-9b876f80-9436-11e9-8ddf-a791ab86744d.png)

File is created at the path. Possibly attempting to read from that location before the file is created.

GNUPG 2.2.15 installed
VSCode 1.35.1

**Comment by majkinetor** [comment]
I have this problem too. Encryption works, but decryption shows that message.

File exists BUT gpg can't open it for some reason. 

```
> gpg tmp-12104k1A2yiGN0KNN
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: can't open 'tmp-12104k1A2yiGN0KNN'
 
#works
> cat tmp-12104k1A2yiGN0KNN | gpg
```

Not sure what is wrong with generated file, it looks totally the same both in encoding and in content as the one I created by hand by copy pasting encrypted text into new file. Copying or renaming the file doesn't work either. 

gpg 2.4.0
Windows 10

**Comment by jvalecillos** [comment]
I haven't had the time to verify this bug because I don't use Windows. But I think I know what it is and it is related with a dependency.
Once I have an updated I will report here.

**Comment by kiwikoda** [comment]
I can report the same issue happening for me. Works if I pipe through 'type'.

```
>gpg tmp-340565MexqF3c4c8g
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: can't open 'tmp-340565MexqF3c4c8g'

#works
>type tmp-340565MexqF3c4c8g | gpg
```

Interestingly, it also works if I first move the temp file into my My Documents folder. I can then use the first method without piping.

**Comment by jvalecillos** [comment]
I've been investigating the issue and I managed to reproduce it as described by @majkinetor. The file exists but the `gpg` command cannot "see" it. The file in question is created from the selected text in order to process it with the command and I'm using a third party gpg library (that in turns is a wrapper for the gpg command), the file itself is created using the `tmp` library. It seems to me that it is a permissions issue.
I will continue checking if I can find a solution. Thanks for the help to all of you.
