### ISSUE TITLE
Update vscode-engine from v1.17 to v1.74

### ISSUE THREAD

**Issue by mariogarridopt** [jvalecillos/vscode-gpg#17]
I'm having some trouble running the current implementation of the code, I think there are some deprecated requirements.

Can I upgrade the engine?

**Comment by jvalecillos** [comment]
I checked around this and my decision is that I will update the engine but not to the "latest" version since that would potentially leave out people that for some reason are using an older version of the IDE. Instead. Of course, the current one is ancient. I settled for keeping 1 year compatibility with the engine, that would be enough for new features (consider the fact that even with the current one the extension still works).
Also, while checking on this I discovered that the test dependencies split from the main engine. That brings another problem, there is no documentation and examples of how to have unit tests in JavaScript with the newer version. So, my plan is:

1. Delete the current unit tests (that are not actually covering anything).
2. Update the version of the engine.
3. Migrate the extension to TypeScript for better support moving forward.

In any case, I will create a separate PR to update the engine to the version I intend.
